### PR TITLE
New Feature: Change card list

### PR DESCRIPTION
**Pull request by JEricaM**
Hi, I've implemented a new feature that permit to the user to change che card's list on the calendar in order to see the change also on trello.

I would like you to consider adding this feature to the original git to allow everyone to use it.

### CODE REVIEW

**Comment by jblankenhorn** [comment]
@JEricaM Thank you very much. Could you please make some adjustments
- Please keep everything in english. We currently have no i18n mechanism.
- change list button does not work in chrome for me
- please keep all the actions in the "..." button ... the 2nd button breaks the small layout.

Thank you
Jan

**Comment by JEricaM** [comment]
Hi.

> Please keep everything in english. We currently have no i18n mechanism.
Now it should be all in English, sorry for that.

> change list button does not work in chrome for me
Mmm I don't understand why, I tried in Chrome only and it work for me. It still not working??

> please keep all the actions in the "..." button ... the 2nd button breaks the small layout. 
Fixed that! Now it's only in the "..." button

Hope that now all works!

**Comment by JEricaM** [comment]
Thank you for the merge. I hope I will be able to help more :)

**Comment by CanKattwinkel** [comment]
@JEricaM @jblankenhorn 

I had to revert the changes for quality assurance reasons. Each card currently causes an HTTP Request. This is not practicable. Please consume already existing data.  

I'll provide a new implementation that fetches the information just when the context menu is opened.

**Comment by JEricaM** [comment]
oh I understand, I'll try to implement a different way to retrieve these informations! Thank you

**Pull request merged**
